name: Deploy to GitHub Pages

on:
  push:
    branches:
      - miles
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install required dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential python3

      - name: Install dependencies and build the project
        run: cd reactApp && export CI=false && rm -rf node_modules package-lock.json && npm install && npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: reactApp/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
